apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pods
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ferncnn46/backend:v1
        env:
          - name: DATABASE_URL
            value: mysql://dashboard_user:NR4m3N&83&On@mysql:3306/dashboard_db
          - name: JWT_SECRET
            value: 4cFy8ZGbZ5BgcaYtuOhQAuLW6p7F5VMi
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"  
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30002
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 11
