apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
data:
  mysql-user: ZGFzaGJvYXJkX3VzZXI=
  mysql-root-password: TlI0bTNOJjgzJk9u
  mysql-database: ZGFzaGJvYXJkX2Ri
  root_password: cm9vdA==